steps:
  # This one step replaces the builder, the registry, and the deploy setup
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--source'
      - '.'  
      - '--region'
      - '$_DEPLOY_REGION'
      - '--allow-unauthenticated'

substitutions:
  _SERVICE_NAME: eappserver
  _DEPLOY_REGION: europe-west1

options:
  logging: CLOUD_LOGGING_ONLY